version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./15-grafana/ds:/etc/grafana/datasources
    - ./15-grafana/dash:/etc/grafana/dashboards
    - ./15-grafana/plugins:/etc/grafana/plugins
    networks:
    - my-network2
    ports:
    - 3000:3000

networks:
  my-network2:
    driver: overlay
    attachable: true

volumes:
  grafana-storage: {}
