---
- name: Start Docker's container. NGINX.

  hosts: new
  tasks:

    - name: Копирование настроек Прокси-сервера
      ansible.builtin.copy:
        src: /etc/systemd/system/docker.service.d/
        dest: /etc/systemd/system/docker.service.d/
        mode: '0644'

    - name: Перечитывание юнитов сервисов
      command: systemctl daemon-reload

    - name: Рестарт демона Docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: Копирование файлов NGINX на удаленные серверы
      ansible.builtin.copy:
        src: ./nginx/
        dest: ./nginx/
        mode: '0644'

    - name: Запуск контейнера
      community.docker.docker_container:
        name: nginx-test4
        image: nginx:latest
        state: started
        restart: true
        ports:
          - "8081:80"
        volumes:
          - "./nginx/html:/usr/share/nginx/html"
          - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      environment: "{{ proxy_env }}"
