version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
    - "8081:80"
#    secrets:
#    - source:
#      target:
    configs:
    - source: nginx.conf
      target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: global
    networks:
    - myNetwork

  pg:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=13572468QWER
    volumes:
    - type: bind
      source: ./data
      target: /data/pg
    deploy:
      placement:
        constraints:
          - "node.labels.pg_db == true"
    networks:
    - myNetwork

networks:
  myNetwork:
    driver: overlay

# secrets:
configs:
  nginx.conf:
    external: true
    
